[package]
name = "dold-kan"
version = "0.1"
lean_version = "leanprover-community/lean:3.45.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d2f303d2cd813ffb1750c34c962048ffd137b733"}
